name: NodeJS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: AutoModality/action-clean@v1
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install Yarn
      run: npm install --global yarn
    - name: Install Lerna
      run: npm install --global lerna
    - name: Restore Project
      run: yarn
    - name: Restore Bootstrap Project
      run: yarn bootstrap
    - name: Build
      run: yarn build:main
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
       name: node-app
       path: packages/main/build
       
  deploy:
    permissions:
      contents: none
    runs-on: self-hosted
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
    - uses: AutoModality/action-clean@v1
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app
    #- name: SCP Files
    #  uses: actions/checkout@master
    - name: List  
      run: ls
